### ISSUE TITLE
2425-W-004 IWTS Artist data ETL

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-iwts#1]
Work Order https://docs.google.com/document/d/1-agbLAyTtHIt2W-fTWsEWe--q6g_HRGnmAJd1yiaOws/edit#heading=h.phzh70cof3ne

```[tasklist]
### Tasks
- [ ] https://github.com/culturecreates/artsdata-planet-iwts/issues/2
- [ ] https://github.com/culturecreates/artsdata-planet-iwts/issues/3
- [ ] https://github.com/culturecreates/artsdata-planet-iwts/issues/4
- [ ] https://github.com/culturecreates/artsdata-planet-iwts/issues/5
- [ ] https://github.com/culturecreates/artsdata-planet-iwts/issues/6
```

**Comment by saumier** [comment]
Waiting for Frederic to communicate IWTS API so we can evaluate work.

**Comment by SkipTay** [comment]
Hi there.  I have built a prototype for the API.

here are the key notes.  as of right now I am waiting on the new fields to be implemented in the database from Ryan and Stephen.

I can provide the url for api access and the command line access.  Not sure if this should be done here or in email.  if this is a private project please advise its is secure and I can provide these items here.

Here are my current notes from the file.
/*
* Skip created API for the CAPACOA Arts Data Graph Project.
* Created June 13, 2024.
* 
 * This file will be used to allow arts data to connect and get performer info for  Open Data.
* 
 * Files added for this API to work:
* - Added a line in the .htaccess file to keep the environment variable hidden.
* - Added api_requests.log to check requests. Periodically, we should check to ensure only the arts data graph is connecting.
* 
 * Key functionality:
* - Force HTTPS
* - Rate limiting: May need to check the logs once the data is accessed to ensure our settings are within the Arts Data requirements.
* - Includes the database connection file.
* - Created log function as per above.
* - Validate the API key, connect to the database, return the data in JSON format.
* 
 * Currently Testing:
* - Current query only grabs a specific performerid that is one of Skips applications for testing.
* - Not interacting with any other performer data currently.
* 
 * To Do:
* - Update query once the field names in the performer table are updated (performerwebsite_2, performerwebsite_3, performerwebsite_4, performerwebsite_5, performer_type, performer_description, consent).
* - Determine OpenData access process. if the request will becoming from a specific ip or domain we can limit access that those specific connection.
*/

**Comment by saumier** [comment]
Need help from Skip to call API.

See email:

> Hi Skip,
> 
> Thanks for sending me access to your API in development.
> 
> I tried a call from my local PC but I get the following error (I replaced the key you sent me with stars)
> 
> https://iwanttoshowcase.ca/apiiwts.php?api_key=**********
> —> {"error": "Unauthorized access. Invalid API key.", "received_api_key": "****" }
> 
> I also get the same error message with curl:
> 
> curl -H "X-API-Key: ***" https://iwanttoshowcase.ca/apiiwts.php  
> —> {"error":"Unauthorized access. Invalid API key.","received_api_key":""}
> 
> 
> How do you suggest I proceed?
> 
> Regarding restricting access: I don’t have a permanent IP address.
> 
> Doc from Github: "For scripted calling of IP addresses we are using Github workflows hosted in Azure and subsequently have the same IP address ranges as the Azure datacenters. Since there are so many IP address ranges for GitHub-hosted runners, we do not recommend that you use these as allowlists for your internal resources."
> 
> From what I can research, the domain [github.com](http://github.com/) <http://github.com/> should allow you to restrict access. Perhaps we can test this after I figure out how to call your API from my local PC.
> 
> Regards,
> Gregory

**Comment by SkipTay** [comment]
Sorry, just sent the full key. For some reason only part of the key pasted in my first text msg.

Let me know now that you have the full key if you get the result

Skip Taylor
Performing Arts Program Manager
Organization of Saskatchewan Arts Councils (OSAC)
Phone: (306) 586-1253
***@***.******@***.***>

**Comment by saumier** [comment]
@SkipTay Data received from API 

```
[
  {
    "performerid": 4,
    "performer_name": "Skip Taylor",
    "performer_country": "Canada",
    "performer_website1": "http://www.osac.ca/",
    "performance_category": "Music",
    "performance_subgenre1": "Cabaret",
    "performer_pronouns": "He/Him"
  }
]
```

@SkipTay Is this a complete set of properties or are you planning to add/remove properties? I am wondering when I should begin working on mapping these to schema.org and/or wikidata.org?

**Comment by SkipTay** [comment]
That is correct.  currently only sending 1 test artist.  I am waiting for Ryan to complete his work and add the additional fields.  Once the fields are added I will update the API to send all opt in artist profiles and all the requested fields.

**Comment by SkipTay** [comment]
Hi Gregory,

The new fields were added to the IWTS production tables.  I have updated the API to include the new fields.  I have sent the output to @fjjulien to confirm the output is as he expected, but if you want to review now you can using the same url provided earlier.  

Currently it is still just the one test  performer, but the field and JSON structure should be there.

**Comment by fjjulien** [comment]
I reviewed the output against the [IWTS Open Data Model document](https://docs.google.com/document/d/14SHgIWuItkp8lnmeculEctfyLc0YV6CVuZRX4e8h0q0/edit?usp=sharing). Everything is good except:

1. For `performer_country`, the stored value should be an ISO 3166-1 alpha-2 code. There are detailed instructions and links in the document on how it should be implemented. According to a comment by Ryan in the doc, this should have been implemented and older values should have been replaced by Steven.
2. For the `performer_type`, for interoperability purposes, the stored values should preferably be as per the Schema labels: Person, PerformingGroup, Organization. This said, this mapping can easily be done in Artsdata. Either way is fine. It's not as big a deal as the country two-letter codes.

Keep up the good work!

**Comment by SkipTay** [comment]
I haven’t officially got word from Ryan that the work was complete.  I suspect they may run a query to replace the existing Country codes this weekend.  I should have known the schema bit.  Again I’ll wait until the work Ryan is doing is complete before coding that.  Stephen may already be coding those values for performer-type.  I simply put a value in that field to be sure it was returned.

**Comment by SkipTay** [comment]
HI all.

The fields are all working as expected now and I believe the output is in a format you will expect.  I have sent an image to Frederic for the output.  Gregory if you want to call the api and confirm the output suits your needs?   The 3 profiles included currently are test profiles so they should not be loaded into OpenData, but they are marked with  consent.  Once you approve the output I will remove consent from these  3 profiles and we will ahve to wait for official consent from real profiles.  I have attached a jpg of the json output for reference.

![api json output](https://github.com/user-attachments/assets/d6784a5b-6324-4778-b72a-9faf096c5f5c)

**Comment by fjjulien** [comment]
As I wrote over email, the output looks as agreed upon in the open data model. 👍

**Comment by saumier** [comment]
@fjjulien @SkipTay I'll review the API output with my team and complete the WO estimate.

**Comment by saumier** [comment]
@dev Please take a look at the output from the IWTS API and estimate an ETL into Artsdata.  Here is a reference doc https://docs.google.com/document/d/14SHgIWuItkp8lnmeculEctfyLc0YV6CVuZRX4e8h0q0/edit but please estimate only the first step which is to load the data as-is using the same property names as the API with prefix `https://iwanttoshowcase.ca/vocabulary#`

**Comment by SkipTay** [comment]
The API will once we reconcile, include the Open Data Unique Identifier and the wikidata unique identifier as well.  But that will take a bit of development on our side yet.

**Comment by fjjulien** [comment]
Note: I already mapped IWTS's Performance Category vocabulary to Artsdata and Wikidata. The mapping is available in [this spreadsheet](https://docs.google.com/spreadsheets/d/1INFFgxF0sOOGDer6Qeo21VYJXw8m2i_ACTqCHFNPBSM/edit?usp=sharing).

**Comment by fjjulien** [comment]
@saumier : @SkipTay performed an initial reconciliation in Open Refine and he intends to add the Artsdata identifiers to the IWTS database. However, I do not think we are extraction IDs from the IWTS database yet.

1. Does it make sense to add the Artsdata ID to the ETL or would it be preferable to only send Artsdata IDs one-way, from Artsdata to IWTS? 
2. If the latter, how can Skip pass his reconciliation work on, so it can be added to Artsdata?
